project:
  type: website

website:
  title: "iamgianluca"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/iamgianluca
      - icon: twitter
        href: https://twitter.com/HeyIamGianluca
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    # css: styles.css

execute:
  freeze: auto

